name: Label release

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  label_master_pr:
    if: github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/release_labeler.yml
  label_develop_pr:
    if: github.base_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        if : startsWith(github.head_ref, 'sandbox/') || startsWith(github.head_ref, 'resolve')
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/release_labeler.yml